### PR TITLE
Triangle

### PR DESCRIPTION
**Pull request by fravij99**
We implemented a very useful shape in ray tracing theory which is Triangle! 
This shape stands on the base of complex figures in computer graphics and, by meshing enough triangles, it is possible tom generate any desired shape. 
We started from implementig the Triangle class containing calculateNormal (calculates the normal of the triangle), calculateArea and rayIntersection. The last method implement the triangular coordinates $(u, v)$ to process the intersection point with a ray and make a must on the conditions of u and v weather or not to save the intersection. 
We also implemented the TriangleMesh class which build a solid by mashing all the possible triangle's cominations given an amount of vertices. 

Tetrahedron:
img

Ottahedron:
img

Dodecahedron:
img

Icosahedron:
img

### CODE REVIEW

**Comment by fravij99** [comment]
I also implemented a functionality that allow the user to read a .txt file with vertices and faces and automatically mesh all the faces. 

This is the result with a bird:

image

**Comment by matteopicciolini** [comment]
That's sounds great! It seems like a great idea to implement the triangle mesh to create complex figures. It also seems that the work done so far is very good!

I'm looking at the code to help you with the difficulties you encountered. I have modified the base branch of this PR because it was set to `master` instead of `compiler,` making things more organized. Before fixing the error related to the transformation, I note that the test `testFurnace()` has issues starting from commit dfd061b663877d505c7440c768138377cf0a8a0c. This prevents proper building of the CI builds.

**Comment by matteopicciolini** [comment]
I found and fixed the error in the testFurnace(). It was an incorrect setting in the test regarding the number of rays:
```PathTracer pathTracer = new PathTracer(world, Black, pcg, 5, 100, 101);```
instead of:
```PathTracer pathTracer = new PathTracer(world, Black, pcg, 1, 100, 101);```
Unfortunately, that wasn't the only error in the CI builds. Now, an error has arisen concerning the test of the Triangle class.

**Comment by fravij99** [comment]
> I found and fixed the error in the `testFurnace()`. It was an incorrect setting in the test regarding the number of rays: `PathTracer pathTracer = new PathTracer(world, Black, pcg, 5, 100, 101);` instead of: `PathTracer pathTracer = new PathTracer(world, Black, pcg, 1, 100, 101);` Unfortunately, that wasn't the only error in the CI builds. Now, an error has arisen concerning the test of the Triangle class.

Thanks Matteo for noticing this error in the `testFurnace()`! Probably there are more problems on triangle tests so I will correct them as soon as possible

**Comment by matteopicciolini** [comment]
To try to narrow down the issue #20, I generated an animation by rotating the branch (not the camera!). What results is interesting because the rotation occurs around the Z-axis, but with respect to the position (0,0,0). The reason why nothing is visible in the bird's image could be that the shape ended up behind the camera or below the plane? I also noticed that for certain angles, there are some suspicious shadows that don't seem natural. Could they be due to a bug in the implementation of rayIntersection in Triangle? Indeed, the tests are failing...

output

**Comment by fravij99** [comment]
To generate shapes like birds I read a .obj file and I transfrom this file .obj into a .txt file as the following python script. 
`import trimesh
import numpy as np

file_path = "/content/ваз 2108.obj"
mesh = trimesh.load(file_path)

if isinstance(mesh, trimesh.Scene):
    # If the OBJ file contains multiple objects, take only the first one
    mesh = mesh.geometry[list(mesh.geometry.keys())[0]]

# Get the vertices and triangles
vertices = mesh.vertices
triangles = mesh.faces

# Determine the maximum and minimum values for each vertex dimension
x_min = np.min(vertices[:, 0])
x_max = np.max(vertices[:, 0])
y_min = np.min(vertices[:, 1])
y_max = np.max(vertices[:, 1])
z_min = np.min(vertices[:, 2])
z_max = np.max(vertices[:, 2])

# Normalize the vertices to the range [0, 1]
normalized_vertices = (vertices - [x_min, y_min, z_min]) / [x_max - x_min, y_max - y_min, z_max - z_min]

# Open the output file for writing
output_file = open("output.txt", "w")

# Write the normalized vertices to the file
for vertex in normalized_vertices:
    output_file.write(f"v {vertex[0]} {vertex[1]} {vertex[2]}\n")

# Write the triangles to the file
for triangle in triangles:
    output_file.write(f"f {triangle[0] + 1} {triangle[1] + 1} {triangle[2] + 1}\n")

# Close the output file
output_file.close()
`

As soon as Java has some compatibility problem with python, I will put the script on the same folder of the whole project.

**Comment by fravij99** [comment]
`import trimesh
import numpy as np

file_path = "/content/ваз 2108.obj"
mesh = trimesh.load(file_path)

if isinstance(mesh, trimesh.Scene):
    # If the OBJ file contains multiple objects, take only the first one
    mesh = mesh.geometry[list(mesh.geometry.keys())[0]]

# Get the vertices and triangles
vertices = mesh.vertices
triangles = mesh.faces

# Determine the maximum and minimum values for each vertex dimension
x_min = np.min(vertices[:, 0])
x_max = np.max(vertices[:, 0])
y_min = np.min(vertices[:, 1])
y_max = np.max(vertices[:, 1])
z_min = np.min(vertices[:, 2])
z_max = np.max(vertices[:, 2])

# Normalize the vertices to the range [0, 1]
normalized_vertices = (vertices - [x_min, y_min, z_min]) / [x_max - x_min, y_max - y_min, z_max - z_min]

# Open the output file for writing
output_file = open("output.txt", "w")

# Write the normalized vertices to the file
for vertex in normalized_vertices:
    output_file.write(f"v {vertex[0]} {vertex[1]} {vertex[2]}\n")

# Write the triangles to the file
for triangle in triangles:
    output_file.write(f"f {triangle[0] + 1} {triangle[1] + 1} {triangle[2] + 1}\n")

# Close the output file
output_file.close()
`

**Comment by fravij99** [comment]
I almost fixed all the main problems with transformations and i realized an images with two birds including antialiasing method and tharts teh result:
image

**Comment by matteopicciolini** [comment]
Below I show some animations created with the code in its current state. In the first one, I use a rotation directly applied to the icosahedron. In the second one, the rotation is applied to the camera instead. It can be noticed that when applying the rotation to the shape created with triangles, the animation exhibits some bugs, possibly related to issue #20.

output


output-min

**Comment by fravij99** [comment]
I rolved part of the bug presented in that pull request and I modified the compiler to accept files from .txt format. I generated a complex image by external file txt:

plakAnimals

**Comment by fravij99** [comment]
I succeeded in fix all problem, Beta version v1.1.0 of our code is now released.

**Pull request closed without merging**
